on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup typst
        uses: typst-community/setup-typst@v4.2
        with:
          typst-version: 0.12
      - name: Make
        run: |
          make all
