on:
  pull_request:
    types: [closed]

jobs:
  delete_from_r2:
    name: Delete PDF from r2
    runs-on: ubuntu-latest
    steps:
      - id: delete_assets_r2
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URL: https://api.ajr.dev/files/austin-rovge-resume-draft-${{ github.event.number }}.pdf
        run: |
          curl $URL -s -o /dev/null -f -X DELETE -H 'X-API-Key: '$API_KEY''
