name: Build
on:
  pull_request

jobs:
  add_building_comment:
    name: Add building comment
    needs: upload_draft_pdf_to_r2
    runs-on: ubuntu-latest
    steps:
    - name: Find existing comment
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{ github.event.number }}
        comment-author: 'github-actions[bot]'
    - name: Update/add comment with remote link
      uses: peter-evans/create-or-update-comment@v2
      continue-on-error: true
      with:
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        issue-number: ${{ github.event.number }}
        edit-mode: replace
        body: |
            Building for commit ${{ github.event.pull_request.head.sha }}
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get install -y texlive texlive-luatex texlive-latex-extra fonts-freefont-ttf
      - name: Make
        run: |
          make all
      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: austin-rovge-resume.pdf
  upload_draft_pdf_to_r2:
    name: Upload draft PDF
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: resume
      - id: upload_assets_r2
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URL: https://api.ajr.dev/files/austin-rovge-resume-draft-${{ github.event.number }}.pdf
        run: |
          curl $URL -s -o /dev/null -f -X PUT -H 'X-API-Key: '$API_KEY'' -H 'Content-Type: document' --data-binary @austin-rovge-resume.pdf
  link_pdf_to_pr_comment:
    name: Link PDF to PR comment
    needs: upload_draft_pdf_to_r2
    runs-on: ubuntu-latest
    steps:
    - name: Find existing comment
      uses: peter-evans/find-comment@v2
      id: find_comment
      with:
        issue-number: ${{ github.event.number }}
        comment-author: 'github-actions[bot]'
    - name: Update/add comment with remote link
      uses: peter-evans/create-or-update-comment@v2
      continue-on-error: true
      with:
        comment-id: ${{ steps.find_comment.outputs.comment-id }}
        issue-number: ${{ github.event.number }}
        edit-mode: replace
        body: |
            <a href="https://api.ajr.dev/files/austin-rovge-resume-draft-${{ github.event.number }}.pdf" target="_blank">https://api.ajr.dev/files/austin-rovge-resume-draft-${{ github.event.number }}.pdf</a>
