name: Build Resume
on:
  push

jobs:
  build:
    name: Build Resume
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install lualatex
        run: |
          apt-get install -y texlive-full lualatex
      - name: Build document
        run: |
          make all
