name: Build
on:
  pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get install -y texlive texlive-luatex texlive-latex-extra fonts-freefont-ttf
      - name: Make
        run: |
          make all
      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: austin-rovge-resume.pdf
  upload_pr_pdf_to_r2:
    name: Upload PR PDF
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: resume
      - id: upload_assets_r2
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URL: https://api.ajr.dev/files/austin-rovge-resume-${{ github.event.number }}.pdf
        run: |
          curl $URL -s -o /dev/null -f -X PUT -H 'X-API-Key: '$API_KEY'' -H 'Content-Type: document' --data-binary @austin-rovge-resume.pdf
  add_link_to_pr_comment:
    name: Add comment
    needs: upload_pr_pdf_to_r2
    env:
      SHA: ${{ github.event.pull_request.head.sha }}
      URL: https://api.ajr.dev/files/austin-rovge-resume-${{ github.event.number }}.pdf
    runs-on: ubuntu-latest
    steps:
      - name: Build comment
        run: |
          echo "Commit: $SHA" > output
          echo "\n" >> output
          echo $URL >> output
      - name: Add remote link to PR comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        continue-on-error: true
        env:
          URL: https://api.ajr.dev/files/austin-rovge-resume-${{ github.event.number }}.pdf
        with:
          issue-number: ${{ github.event.number }}
          body: |
            Commit: ${{ github.event.pull_request.head.sha }}
            $URL
