name: Build
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'

env:
  DATA: ${{ github.event }}

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          echo $DATA
          exit 2
          sudo apt-get install -y texlive texlive-luatex texlive-latex-extra fonts-freefont-ttf
      - name: Make
        run: |
          make all
  upload_pr_pdf_to_r2:
    name: Upload PR PDF
    # if: github.event_name == 'pull_request'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Install deps
        run: |
          echo $github.event_name
          echo $github
          exit 1
          sudo apt-get install -y texlive texlive-luatex texlive-latex-extra fonts-freefont-ttf
      - name: Make
        run: |
          make all
      - id: upload_assets_r2
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URL: https://api.ajr.dev/files/austin-rovge-resume-'${{ github.event.number }}'.pdf
        run: |
          curl '$url' -s -o /dev/null -f -X PUT -H 'X-API-Key: '$API_KEY''  -H 'Content-Type: document' --data-binary @austin-rovge-resume.pdf
  add_link_to_pr_comment:
    name: Add comment
    needs: upload_pr_pdf_to_r2
    runs-on: ubuntu-latest
    steps:
      - name: Add remote link to PR comment
        uses: peter-evans/create-or-update-comment@v1.4.5
        continue-on-error: true
        env:
          SHA: ${{ github.event.pull_request.head.sha }}
          URL: https://api.ajr.dev/files/austin-rovge-resume-'${{ github.event.number }}'.pdf
        with:
          issue-number: ${{ github.event.issue.number }}
          body: |
            Commit: $SHA
            $URL
