on:
  pull_request:
    types: [closed]

jobs:
  delete_from_api:
    name: Delete asset from api
    runs-on: ubuntu-latest
    steps:
      - name: Delete asset from api
        env:
          API_KEY: ${{ secrets.API_KEY }}
          URL: https://api.ajr.dev/files/austin-rovge-resume-draft-${{ github.event.number }}.pdf
        run: |
          curl $URL -s -o /dev/null -f -X DELETE -H 'X-API-Key: '$API_KEY''
