on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup typst
        uses: typst-community/setup-typst@v3
        with:
          typst-version: 0.12
      - name: Make
        run: |
          make all
      - uses: actions/upload-artifact@v3
        with:
          name: resume
          path: austin-rovge-resume.pdf
  upload:
    name: Upload release assets to GitHub/api.ajr.dev
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: resume
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.3.2
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: Upload release asset to GitHub
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: ./austin-rovge-resume.pdf
          asset_name: austin-rovge-resume.pdf
          asset_content_type: application/pdf
      - name: Upload release asset to api.ajr.dev
        env:
          API_KEY: ${{ secrets.API_KEY }}
        run: |
          curl https://api.ajr.dev/files/austin-rovge-resume.pdf -s -o /dev/null -f -X PUT -H 'X-API-Key: '$API_KEY'' -H 'Content-Type: document' --data-binary @austin-rovge-resume.pdf
